# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dr.plugin.v1 import host_pb2 as dr_dot_plugin_dot_v1_dot_host__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dr/plugin/v1/host_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HostStub(object):
    """------- Dedup ------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IsKnown = channel.unary_unary(
                '/dr.plugin.v1.Host/IsKnown',
                request_serializer=dr_dot_plugin_dot_v1_dot_host__pb2.IsKnownRequest.SerializeToString,
                response_deserializer=dr_dot_plugin_dot_v1_dot_host__pb2.IsKnownResponse.FromString,
                _registered_method=True)
        self.UpsertImportRow = channel.unary_unary(
                '/dr.plugin.v1.Host/UpsertImportRow',
                request_serializer=dr_dot_plugin_dot_v1_dot_host__pb2.UpsertImportRowRequest.SerializeToString,
                response_deserializer=dr_dot_plugin_dot_v1_dot_host__pb2.UpsertImportRowResponse.FromString,
                _registered_method=True)
        self.StagePath = channel.unary_unary(
                '/dr.plugin.v1.Host/StagePath',
                request_serializer=dr_dot_plugin_dot_v1_dot_host__pb2.StagePathRequest.SerializeToString,
                response_deserializer=dr_dot_plugin_dot_v1_dot_host__pb2.StagePathResponse.FromString,
                _registered_method=True)
        self.WriteAttachment = channel.unary_unary(
                '/dr.plugin.v1.Host/WriteAttachment',
                request_serializer=dr_dot_plugin_dot_v1_dot_host__pb2.WriteAttachmentRequest.SerializeToString,
                response_deserializer=dr_dot_plugin_dot_v1_dot_host__pb2.WriteAttachmentResponse.FromString,
                _registered_method=True)
        self.GetConfig = channel.unary_unary(
                '/dr.plugin.v1.Host/GetConfig',
                request_serializer=dr_dot_plugin_dot_v1_dot_host__pb2.GetConfigRequest.SerializeToString,
                response_deserializer=dr_dot_plugin_dot_v1_dot_host__pb2.GetConfigResponse.FromString,
                _registered_method=True)
        self.SetConfig = channel.unary_unary(
                '/dr.plugin.v1.Host/SetConfig',
                request_serializer=dr_dot_plugin_dot_v1_dot_host__pb2.SetConfigRequest.SerializeToString,
                response_deserializer=dr_dot_plugin_dot_v1_dot_host__pb2.SetConfigResponse.FromString,
                _registered_method=True)
        self.EmitMetric = channel.unary_unary(
                '/dr.plugin.v1.Host/EmitMetric',
                request_serializer=dr_dot_plugin_dot_v1_dot_host__pb2.EmitMetricRequest.SerializeToString,
                response_deserializer=dr_dot_plugin_dot_v1_dot_host__pb2.EmitMetricResponse.FromString,
                _registered_method=True)
        self.EmitLog = channel.unary_unary(
                '/dr.plugin.v1.Host/EmitLog',
                request_serializer=dr_dot_plugin_dot_v1_dot_host__pb2.EmitLogRequest.SerializeToString,
                response_deserializer=dr_dot_plugin_dot_v1_dot_host__pb2.EmitLogResponse.FromString,
                _registered_method=True)


class HostServicer(object):
    """------- Dedup ------------------------------------------------------
    """

    def IsKnown(self, request, context):
        """IsKnown asks whether (plugin_id, external_id) has already been
        ingested in any prior run. Cheap; index-only.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertImportRow(self, request, context):
        """------- Importer persistence --------------------------------------

        UpsertImportRow lets specialised importers (zotero) write into
        their dedicated table. Generic importers don't need this -- the
        host writes platform.plugin_items automatically from SyncEvent
        items emitted during Sync.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StagePath(self, request, context):
        """------- File staging ----------------------------------------------

        StagePath returns a writable path in the shared dr_uploads volume
        the plugin may write to (host creates the directory, sets perms).
        Use when the plugin shares the volume with the host (the common
        production case) -- avoids round-tripping bytes through gRPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteAttachment(self, request, context):
        """WriteAttachment is the fallback path for plugins that don't share
        the volume (or for very small blobs). Bytes flow over the wire;
        the host writes them to dr_uploads and returns the path it used.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfig(self, request, context):
        """------- Config / secrets ------------------------------------------

        GetConfig returns the plugin's current decrypted config blob.
        Equivalent to what Hello.config carried at startup; useful when
        the plugin wants to re-read after a SetConfig.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetConfig(self, request, context):
        """SetConfig persists a new config blob (encrypted at rest). Used
        when the plugin runs an interactive auth flow (e.g. OAuth) and
        needs to save the resulting token.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmitMetric(self, request, context):
        """------- Observability ---------------------------------------------

        EmitMetric pushes a single counter/gauge/histogram observation to
        the host's prometheus registry, tagged with the plugin id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmitLog(self, request, context):
        """EmitLog forwards a log line to the host's structured logger so
        plugin output ends up in the same stream as host output. Plugins
        may also write to stderr; that's captured separately.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HostServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IsKnown': grpc.unary_unary_rpc_method_handler(
                    servicer.IsKnown,
                    request_deserializer=dr_dot_plugin_dot_v1_dot_host__pb2.IsKnownRequest.FromString,
                    response_serializer=dr_dot_plugin_dot_v1_dot_host__pb2.IsKnownResponse.SerializeToString,
            ),
            'UpsertImportRow': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertImportRow,
                    request_deserializer=dr_dot_plugin_dot_v1_dot_host__pb2.UpsertImportRowRequest.FromString,
                    response_serializer=dr_dot_plugin_dot_v1_dot_host__pb2.UpsertImportRowResponse.SerializeToString,
            ),
            'StagePath': grpc.unary_unary_rpc_method_handler(
                    servicer.StagePath,
                    request_deserializer=dr_dot_plugin_dot_v1_dot_host__pb2.StagePathRequest.FromString,
                    response_serializer=dr_dot_plugin_dot_v1_dot_host__pb2.StagePathResponse.SerializeToString,
            ),
            'WriteAttachment': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteAttachment,
                    request_deserializer=dr_dot_plugin_dot_v1_dot_host__pb2.WriteAttachmentRequest.FromString,
                    response_serializer=dr_dot_plugin_dot_v1_dot_host__pb2.WriteAttachmentResponse.SerializeToString,
            ),
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=dr_dot_plugin_dot_v1_dot_host__pb2.GetConfigRequest.FromString,
                    response_serializer=dr_dot_plugin_dot_v1_dot_host__pb2.GetConfigResponse.SerializeToString,
            ),
            'SetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetConfig,
                    request_deserializer=dr_dot_plugin_dot_v1_dot_host__pb2.SetConfigRequest.FromString,
                    response_serializer=dr_dot_plugin_dot_v1_dot_host__pb2.SetConfigResponse.SerializeToString,
            ),
            'EmitMetric': grpc.unary_unary_rpc_method_handler(
                    servicer.EmitMetric,
                    request_deserializer=dr_dot_plugin_dot_v1_dot_host__pb2.EmitMetricRequest.FromString,
                    response_serializer=dr_dot_plugin_dot_v1_dot_host__pb2.EmitMetricResponse.SerializeToString,
            ),
            'EmitLog': grpc.unary_unary_rpc_method_handler(
                    servicer.EmitLog,
                    request_deserializer=dr_dot_plugin_dot_v1_dot_host__pb2.EmitLogRequest.FromString,
                    response_serializer=dr_dot_plugin_dot_v1_dot_host__pb2.EmitLogResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dr.plugin.v1.Host', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dr.plugin.v1.Host', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Host(object):
    """------- Dedup ------------------------------------------------------
    """

    @staticmethod
    def IsKnown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dr.plugin.v1.Host/IsKnown',
            dr_dot_plugin_dot_v1_dot_host__pb2.IsKnownRequest.SerializeToString,
            dr_dot_plugin_dot_v1_dot_host__pb2.IsKnownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertImportRow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dr.plugin.v1.Host/UpsertImportRow',
            dr_dot_plugin_dot_v1_dot_host__pb2.UpsertImportRowRequest.SerializeToString,
            dr_dot_plugin_dot_v1_dot_host__pb2.UpsertImportRowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StagePath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dr.plugin.v1.Host/StagePath',
            dr_dot_plugin_dot_v1_dot_host__pb2.StagePathRequest.SerializeToString,
            dr_dot_plugin_dot_v1_dot_host__pb2.StagePathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteAttachment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dr.plugin.v1.Host/WriteAttachment',
            dr_dot_plugin_dot_v1_dot_host__pb2.WriteAttachmentRequest.SerializeToString,
            dr_dot_plugin_dot_v1_dot_host__pb2.WriteAttachmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dr.plugin.v1.Host/GetConfig',
            dr_dot_plugin_dot_v1_dot_host__pb2.GetConfigRequest.SerializeToString,
            dr_dot_plugin_dot_v1_dot_host__pb2.GetConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dr.plugin.v1.Host/SetConfig',
            dr_dot_plugin_dot_v1_dot_host__pb2.SetConfigRequest.SerializeToString,
            dr_dot_plugin_dot_v1_dot_host__pb2.SetConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmitMetric(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dr.plugin.v1.Host/EmitMetric',
            dr_dot_plugin_dot_v1_dot_host__pb2.EmitMetricRequest.SerializeToString,
            dr_dot_plugin_dot_v1_dot_host__pb2.EmitMetricResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmitLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dr.plugin.v1.Host/EmitLog',
            dr_dot_plugin_dot_v1_dot_host__pb2.EmitLogRequest.SerializeToString,
            dr_dot_plugin_dot_v1_dot_host__pb2.EmitLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
