# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dr.plugin.v1 import plugin_pb2 as dr_dot_plugin_dot_v1_dot_plugin__pb2
from dr.plugin.v1 import types_pb2 as dr_dot_plugin_dot_v1_dot_types__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dr/plugin/v1/plugin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PluginStub(object):
    """------- Lifecycle (all plugins implement these three) -------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Hello = channel.unary_unary(
                '/dr.plugin.v1.Plugin/Hello',
                request_serializer=dr_dot_plugin_dot_v1_dot_plugin__pb2.HelloRequest.SerializeToString,
                response_deserializer=dr_dot_plugin_dot_v1_dot_plugin__pb2.HelloResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/dr.plugin.v1.Plugin/Ping',
                request_serializer=dr_dot_plugin_dot_v1_dot_plugin__pb2.PingRequest.SerializeToString,
                response_deserializer=dr_dot_plugin_dot_v1_dot_plugin__pb2.PingResponse.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/dr.plugin.v1.Plugin/Shutdown',
                request_serializer=dr_dot_plugin_dot_v1_dot_plugin__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=dr_dot_plugin_dot_v1_dot_plugin__pb2.ShutdownResponse.FromString,
                _registered_method=True)
        self.ListCollections = channel.unary_unary(
                '/dr.plugin.v1.Plugin/ListCollections',
                request_serializer=dr_dot_plugin_dot_v1_dot_plugin__pb2.ListCollectionsRequest.SerializeToString,
                response_deserializer=dr_dot_plugin_dot_v1_dot_plugin__pb2.ListCollectionsResponse.FromString,
                _registered_method=True)
        self.Sync = channel.unary_stream(
                '/dr.plugin.v1.Plugin/Sync',
                request_serializer=dr_dot_plugin_dot_v1_dot_plugin__pb2.SyncRequest.SerializeToString,
                response_deserializer=dr_dot_plugin_dot_v1_dot_types__pb2.SyncEvent.FromString,
                _registered_method=True)
        self.SearchQuery = channel.unary_unary(
                '/dr.plugin.v1.Plugin/SearchQuery',
                request_serializer=dr_dot_plugin_dot_v1_dot_plugin__pb2.SearchQueryRequest.SerializeToString,
                response_deserializer=dr_dot_plugin_dot_v1_dot_plugin__pb2.SearchQueryResponse.FromString,
                _registered_method=True)
        self.SearchFetch = channel.unary_unary(
                '/dr.plugin.v1.Plugin/SearchFetch',
                request_serializer=dr_dot_plugin_dot_v1_dot_plugin__pb2.SearchFetchRequest.SerializeToString,
                response_deserializer=dr_dot_plugin_dot_v1_dot_plugin__pb2.SearchFetchResponse.FromString,
                _registered_method=True)
        self.MarketplaceQuery = channel.unary_unary(
                '/dr.plugin.v1.Plugin/MarketplaceQuery',
                request_serializer=dr_dot_plugin_dot_v1_dot_plugin__pb2.MarketplaceQueryRequest.SerializeToString,
                response_deserializer=dr_dot_plugin_dot_v1_dot_plugin__pb2.MarketplaceQueryResponse.FromString,
                _registered_method=True)
        self.MarketplaceFetchListing = channel.unary_unary(
                '/dr.plugin.v1.Plugin/MarketplaceFetchListing',
                request_serializer=dr_dot_plugin_dot_v1_dot_plugin__pb2.MarketplaceFetchListingRequest.SerializeToString,
                response_deserializer=dr_dot_plugin_dot_v1_dot_plugin__pb2.MarketplaceFetchListingResponse.FromString,
                _registered_method=True)


class PluginServicer(object):
    """------- Lifecycle (all plugins implement these three) -------------
    """

    def Hello(self, request, context):
        """Hello is the first call. The host sends its version + a copy of
        the plugin's resolved config (decrypted, expanded); the plugin
        returns its build info and the capability list it actually
        implements (must be a subset of what the manifest declared).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Ping is the liveness probe. Plugins return immediately.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Shutdown asks the plugin to flush + exit cleanly. The host SIGKILLs
        after a grace period if the plugin doesn't exit on its own.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCollections(self, request, context):
        """------- Importer category -----------------------------------------

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sync(self, request, context):
        """Sync is server-streaming. Plugin emits SyncEvent messages (items,
        progress, errors). The final event MUST be a `summary`. The plugin
        may call back into the host (IsKnown, StagePath, …) on the host
        socket *while* this stream is open -- those are unary RPCs, not
        multiplexed onto the sync stream.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchQuery(self, request, context):
        """------- Search category -------------------------------------------

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchFetch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarketplaceQuery(self, request, context):
        """------- Marketplace category (scaffolded) -------------------------

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarketplaceFetchListing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PluginServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Hello': grpc.unary_unary_rpc_method_handler(
                    servicer.Hello,
                    request_deserializer=dr_dot_plugin_dot_v1_dot_plugin__pb2.HelloRequest.FromString,
                    response_serializer=dr_dot_plugin_dot_v1_dot_plugin__pb2.HelloResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=dr_dot_plugin_dot_v1_dot_plugin__pb2.PingRequest.FromString,
                    response_serializer=dr_dot_plugin_dot_v1_dot_plugin__pb2.PingResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=dr_dot_plugin_dot_v1_dot_plugin__pb2.ShutdownRequest.FromString,
                    response_serializer=dr_dot_plugin_dot_v1_dot_plugin__pb2.ShutdownResponse.SerializeToString,
            ),
            'ListCollections': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCollections,
                    request_deserializer=dr_dot_plugin_dot_v1_dot_plugin__pb2.ListCollectionsRequest.FromString,
                    response_serializer=dr_dot_plugin_dot_v1_dot_plugin__pb2.ListCollectionsResponse.SerializeToString,
            ),
            'Sync': grpc.unary_stream_rpc_method_handler(
                    servicer.Sync,
                    request_deserializer=dr_dot_plugin_dot_v1_dot_plugin__pb2.SyncRequest.FromString,
                    response_serializer=dr_dot_plugin_dot_v1_dot_types__pb2.SyncEvent.SerializeToString,
            ),
            'SearchQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchQuery,
                    request_deserializer=dr_dot_plugin_dot_v1_dot_plugin__pb2.SearchQueryRequest.FromString,
                    response_serializer=dr_dot_plugin_dot_v1_dot_plugin__pb2.SearchQueryResponse.SerializeToString,
            ),
            'SearchFetch': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchFetch,
                    request_deserializer=dr_dot_plugin_dot_v1_dot_plugin__pb2.SearchFetchRequest.FromString,
                    response_serializer=dr_dot_plugin_dot_v1_dot_plugin__pb2.SearchFetchResponse.SerializeToString,
            ),
            'MarketplaceQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.MarketplaceQuery,
                    request_deserializer=dr_dot_plugin_dot_v1_dot_plugin__pb2.MarketplaceQueryRequest.FromString,
                    response_serializer=dr_dot_plugin_dot_v1_dot_plugin__pb2.MarketplaceQueryResponse.SerializeToString,
            ),
            'MarketplaceFetchListing': grpc.unary_unary_rpc_method_handler(
                    servicer.MarketplaceFetchListing,
                    request_deserializer=dr_dot_plugin_dot_v1_dot_plugin__pb2.MarketplaceFetchListingRequest.FromString,
                    response_serializer=dr_dot_plugin_dot_v1_dot_plugin__pb2.MarketplaceFetchListingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dr.plugin.v1.Plugin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dr.plugin.v1.Plugin', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Plugin(object):
    """------- Lifecycle (all plugins implement these three) -------------
    """

    @staticmethod
    def Hello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dr.plugin.v1.Plugin/Hello',
            dr_dot_plugin_dot_v1_dot_plugin__pb2.HelloRequest.SerializeToString,
            dr_dot_plugin_dot_v1_dot_plugin__pb2.HelloResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dr.plugin.v1.Plugin/Ping',
            dr_dot_plugin_dot_v1_dot_plugin__pb2.PingRequest.SerializeToString,
            dr_dot_plugin_dot_v1_dot_plugin__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dr.plugin.v1.Plugin/Shutdown',
            dr_dot_plugin_dot_v1_dot_plugin__pb2.ShutdownRequest.SerializeToString,
            dr_dot_plugin_dot_v1_dot_plugin__pb2.ShutdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCollections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dr.plugin.v1.Plugin/ListCollections',
            dr_dot_plugin_dot_v1_dot_plugin__pb2.ListCollectionsRequest.SerializeToString,
            dr_dot_plugin_dot_v1_dot_plugin__pb2.ListCollectionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Sync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dr.plugin.v1.Plugin/Sync',
            dr_dot_plugin_dot_v1_dot_plugin__pb2.SyncRequest.SerializeToString,
            dr_dot_plugin_dot_v1_dot_types__pb2.SyncEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dr.plugin.v1.Plugin/SearchQuery',
            dr_dot_plugin_dot_v1_dot_plugin__pb2.SearchQueryRequest.SerializeToString,
            dr_dot_plugin_dot_v1_dot_plugin__pb2.SearchQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchFetch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dr.plugin.v1.Plugin/SearchFetch',
            dr_dot_plugin_dot_v1_dot_plugin__pb2.SearchFetchRequest.SerializeToString,
            dr_dot_plugin_dot_v1_dot_plugin__pb2.SearchFetchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarketplaceQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dr.plugin.v1.Plugin/MarketplaceQuery',
            dr_dot_plugin_dot_v1_dot_plugin__pb2.MarketplaceQueryRequest.SerializeToString,
            dr_dot_plugin_dot_v1_dot_plugin__pb2.MarketplaceQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarketplaceFetchListing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dr.plugin.v1.Plugin/MarketplaceFetchListing',
            dr_dot_plugin_dot_v1_dot_plugin__pb2.MarketplaceFetchListingRequest.SerializeToString,
            dr_dot_plugin_dot_v1_dot_plugin__pb2.MarketplaceFetchListingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
